// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include "arduino_secrets.h"
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "yourThingIDGenerated";
const char DEVICE_LOGIN_NAME[]  = "yourDeviceLoginNameGenerated";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAbrirTapaChange();

bool estadoTapa = false;
bool abrir = false;

void initProperties() {

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(estadoTapa, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(abrir, READWRITE, 5 * SECONDS, onAbrirTapaChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
